#!/bin/bash
# =============================================================================
# FREQ SOL - Azure Digital Twins Explorer Local Setup
# =============================================================================
# This script sets up a local instance of ADT Explorer for visualizing
# the lidar-twins Digital Twins instance.
#
# Prerequisites:
#   - Node.js 18+
#   - npm
#   - Azure CLI (az) logged in
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADT_EXPLORER_DIR="$SCRIPT_DIR/digital-twins-explorer"
ADT_INSTANCE="lidar-twins"
ADT_HOST="lidar-twins.api.eus2.digitaltwins.azure.net"

echo "=============================================="
echo "FREQ SOL - ADT Explorer Local Setup"
echo "=============================================="
echo ""

# Check prerequisites
check_prereqs() {
    echo "[1/5] Checking prerequisites..."

    if ! command -v node &> /dev/null; then
        echo "ERROR: Node.js is not installed. Please install Node.js 18+"
        exit 1
    fi

    NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VERSION" -lt 18 ]; then
        echo "ERROR: Node.js 18+ required. Found: $(node -v)"
        exit 1
    fi
    echo "  Node.js: $(node -v) OK"

    if ! command -v npm &> /dev/null; then
        echo "ERROR: npm is not installed"
        exit 1
    fi
    echo "  npm: $(npm -v) OK"

    if ! command -v az &> /dev/null; then
        echo "WARNING: Azure CLI not found. You'll need to configure auth manually."
    else
        echo "  Azure CLI: $(az version --query '"azure-cli"' -o tsv) OK"
    fi

    echo ""
}

# Clone ADT Explorer repository
clone_repo() {
    echo "[2/5] Cloning ADT Explorer repository..."

    if [ -d "$ADT_EXPLORER_DIR" ]; then
        echo "  Repository already exists. Pulling latest..."
        cd "$ADT_EXPLORER_DIR"
        git pull origin main
    else
        git clone https://github.com/Azure-Samples/digital-twins-explorer.git "$ADT_EXPLORER_DIR"
    fi

    echo "  Done."
    echo ""
}

# Install dependencies
install_deps() {
    echo "[3/5] Installing dependencies..."

    cd "$ADT_EXPLORER_DIR/client"
    npm install

    echo "  Done."
    echo ""
}

# Configure environment
configure_env() {
    echo "[4/5] Configuring environment for lidar-twins..."

    # Create .env file for local development
    cat > "$ADT_EXPLORER_DIR/client/.env.local" << EOF
# FREQ SOL - lidar-twins Configuration
# Generated by setup.sh

# Azure Digital Twins instance
REACT_APP_ADT_URL=https://${ADT_HOST}

# Optional: Pre-populate instance URL in UI
REACT_APP_DEFAULT_ADT_HOST=${ADT_HOST}
EOF

    echo "  Created .env.local with lidar-twins configuration"
    echo ""
}

# Create launcher script
create_launcher() {
    echo "[5/5] Creating launcher script..."

    cat > "$SCRIPT_DIR/start-explorer.sh" << 'EOF'
#!/bin/bash
# Start ADT Explorer for FREQ SOL lidar-twins instance

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/digital-twins-explorer/client"

echo "Starting ADT Explorer..."
echo "Instance: lidar-twins.api.eus2.digitaltwins.azure.net"
echo ""
echo "Opening browser at http://localhost:3000"
echo "Press Ctrl+C to stop"
echo ""

npm run start
EOF

    chmod +x "$SCRIPT_DIR/start-explorer.sh"

    echo "  Created start-explorer.sh"
    echo ""
}

# Main
main() {
    check_prereqs
    clone_repo
    install_deps
    configure_env
    create_launcher

    echo "=============================================="
    echo "Setup Complete!"
    echo "=============================================="
    echo ""
    echo "To start ADT Explorer:"
    echo "  cd $SCRIPT_DIR"
    echo "  ./start-explorer.sh"
    echo ""
    echo "Then connect to: https://${ADT_HOST}"
    echo ""
    echo "Make sure you're logged into Azure CLI:"
    echo "  az login"
    echo "=============================================="
}

main "$@"
